# -*- coding: utf-8 -*-
"""textfile_size_reducer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXTTqjOR8ms7TDSPDDGDv4WRVHjY3HWw
"""

import os

def reduce_text_file_size(input_file, output_file, target_size_kb):

    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()


    compressed_content = ' '.join(content.split())


    while len(compressed_content.encode('utf-8')) > target_size_kb * 1024:
        compressed_content = compressed_content[:-1]


    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(compressed_content)

    print(f"Reduced file saved as {output_file}, size: {os.path.getsize(output_file) / 1024:.2f} KB")


reduce_text_file_size('input.txt', 'output.txt', 40)